Repository ember-cli/ember-app-blueprint, pull requests merged in 2025-06, with the labels that each got.

#28 make sure we always use strict generators
  files/.ember-cli
Labels: enhancement

#27 Remove unused dependencies
  files/package.json
  tests/default.test.mjs
  tests/helpers.mjs
Labels: enhancement

#35 Adjust the lint command / enforce prettier in CI (our code, not for the output)
  .prettierignore
  eslint.config.mjs
  index.js
  lib/prepend-emoji.js
  package.json
  pnpm-lock.yaml
Labels: internal

#33 Fix NODE_ENV for tests
  files/.env.test
Labels: bug

#38 Change Test mode to Development mode
  files/.env.development
  files/package.json
Labels: bug
