Repository ember-cli/ember-app-blueprint, pull requests merged in 2025-09, with the labels that each got.

#63 reset blueprint to match ember-cli app blueprint (in the next release)
  package.json
Labels: enhancement

#69 Revert "Prepare Stable Release v6.7.0"
  .release-plan.json
  CHANGELOG.md
  package.json
Labels: ignore

#70 add a basic readme
  README.md
Labels: documentation

#81 Correct example usage command in README
  README.md
Labels: documentation

#64 Update the release document to match the ember-cli process
  RELEASE.md
Labels: documentation
